// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_9170ac915b1f24a41a5f1ba25c4e50fc_5d8a0b53_9a0a_4e8b_8d9a_7331ec7e1387 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			return update.value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_9170ac915b1f24a41a5f1ba25c4e50fc_2233584b_7452_4cec_8691_d73320facdc1 : RotationBinding
	{
		public override string CoherenceComponentName => "WorldOrientation";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(coherenceSync.coherenceRotation);
			set => coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldOrientation)coherenceComponent;
			return update.value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldOrientation)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldOrientation();
		}
	}

	public class Binding_9170ac915b1f24a41a5f1ba25c4e50fc_2116804c_2203_4835_8795_5be29b45dbf8 : FloatAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_Animator_4751803303538668738";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override float Value
		{
			get => (float)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, (value));
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Animator_4751803303538668738)coherenceComponent;
			return update.MoveSpeed;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Animator_4751803303538668738)coherenceComponent;
			update.MoveSpeed = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_Animator_4751803303538668738();
		}
	}

	public class Binding_9170ac915b1f24a41a5f1ba25c4e50fc_62ece937_585f_49d3_86f9_aa5abe116859 : BoolAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_Animator_4751803303538668738";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override bool Value
		{
			get => (bool)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, (value));
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Animator_4751803303538668738)coherenceComponent;
			return update.Grounded;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Animator_4751803303538668738)coherenceComponent;
			update.Grounded = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_Animator_4751803303538668738();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Player' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncPlayer_id0 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands		
		private UnityEngine.Animator Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1_CommandTarget;

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncPlayer_id0>();
			if (coherenceSync.TryGetBindingByGuid("be5c5f98-c2c7-4c78-8153-710be3d019d1", "SetTrigger", out Binding Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1))
			{
				Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1_CommandTarget = (UnityEngine.Animator)Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("UnityEngine.Animator.SetTrigger", "(System.String)",
				SendCommand_Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1, ReceiveLocalCommand_Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1, MessageTarget.All, Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (SetTrigger)");
			}
			if (coherenceSync.TryGetBindingByGuid("5d8a0b53-9a0a-4e8b-8d9a-7331ec7e1387", "position", out Binding InternalWorldPosition_Translation_value))
			{
				var clone = new Binding_9170ac915b1f24a41a5f1ba25c4e50fc_5d8a0b53_9a0a_4e8b_8d9a_7331ec7e1387();
				InternalWorldPosition_Translation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldPosition_Translation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("2233584b-7452-4cec-8691-d73320facdc1", "rotation", out Binding InternalWorldOrientation_Rotation_value))
			{
				var clone = new Binding_9170ac915b1f24a41a5f1ba25c4e50fc_2233584b_7452_4cec_8691_d73320facdc1();
				InternalWorldOrientation_Rotation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldOrientation_Rotation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
			if (coherenceSync.TryGetBindingByGuid("2116804c-2203-4835-8795-5be29b45dbf8", "MoveSpeed", out Binding InternalPlayer_id0_UnityEngine__char_46_Animator_4751803303538668738_Player_id0_UnityEngine__char_46_Animator_4751803303538668738_MoveSpeed))
			{
				var clone = new Binding_9170ac915b1f24a41a5f1ba25c4e50fc_2116804c_2203_4835_8795_5be29b45dbf8();
				InternalPlayer_id0_UnityEngine__char_46_Animator_4751803303538668738_Player_id0_UnityEngine__char_46_Animator_4751803303538668738_MoveSpeed.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_Animator_4751803303538668738_Player_id0_UnityEngine__char_46_Animator_4751803303538668738_MoveSpeed)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).MoveSpeed");
			}
			if (coherenceSync.TryGetBindingByGuid("62ece937-585f-49d3-86f9-aa5abe116859", "Grounded", out Binding InternalPlayer_id0_UnityEngine__char_46_Animator_4751803303538668738_Player_id0_UnityEngine__char_46_Animator_4751803303538668738_Grounded))
			{
				var clone = new Binding_9170ac915b1f24a41a5f1ba25c4e50fc_62ece937_585f_49d3_86f9_aa5abe116859();
				InternalPlayer_id0_UnityEngine__char_46_Animator_4751803303538668738_Player_id0_UnityEngine__char_46_Animator_4751803303538668738_Grounded.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_Animator_4751803303538668738_Player_id0_UnityEngine__char_46_Animator_4751803303538668738_Grounded)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).Grounded");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}
		void SendCommand_Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1(MessageTarget target, object[] args)
		{
			var command = new Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1();
			int i = 0;
			command.name = (string)((System.String)args[i++]);
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1(MessageTarget target, object[] args)
		{
			var command = new Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1();
			int i = 0;
			command.name = (string)((System.String)args[i++]);
			ReceiveCommand_Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1(command);
		}

		void ReceiveCommand_Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1(Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1 command)
		{
			var target = Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1_CommandTarget;
			target.SetTrigger((System.String)(command.name));
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1 castedCommand:
					ReceiveCommand_Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncPlayer_id0] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
