// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1 : IEntityCommand
	{
		public string name;

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalPlayer_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1;

		public Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1
		(
			string dataname
		)
		{
			name = dataname;
		}

		public static void Serialize(Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1 commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteShortString(commandData.name);
		}

		public static Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1 Deserialize(IInProtocolBitStream bitStream)
		{
			var dataname = bitStream.ReadShortString();

			return new Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_be5c5f98_c2c7_4c78_8153_710be3d019d1
			(
				dataname
			){};
		}
	}
}
